documentation:
        stage: misc
        image: docker-registry.csc.mpi-magdeburg.mpg.de:5000/ci-images/minimal/latex:jammy
        needs: []
        script:
                - |
                  apt-get update; apt-get install --yes cmake libopenblas-dev  libhdf5-dev doxygen graphviz gcc gfortran
                  mkdir -p build.doc
                  cd build.doc
                  cmake ../ -DDEBUG=OFF -DMATLAB=OFF -DEXAMPLES=OFF -DDOC=ON
                  make doc
                  rm -f doc/*.tar.gz
                  if [ -z "$CI_COMMIT_TAG" ]; then export CI_COMMIT_TAG=$(git describe) ; fi
                  tar --transform="s/explore-html\///g" -czvf mepack-${CI_COMMIT_TAG}-docs.tar.gz doc/explore-html/
        artifacts:
            when: on_success
            expire_in: 1d
            paths:
                - build.doc/mepack-*.tar.gz
