# Function Names
s/DLA_SMALL_SOLVE4/SLA_SMALL_SOLVE4/g
s/DLA_SMALL_SOLVE8/SLA_SMALL_SOLVE8/g
s/DLA_DTRMM_FIX/SLA_STRMM_FIX/g
s/DLA_GEAXA/SLA_GEAXA/g
s/DLA_QTRMM2/SLA_QTRMM2/g
s/DLA_SORT_EV/SLA_SORT_EV/g
s/DLA_SORT_GEV/SLA_SORT_GEV/g
s/DLA_GEAXB/SLA_GEAXB/g
s/DLA_ITRANSPOSE/SLA_ITRANSPOSE/g
s/DARCHINIT/SARCHINIT/g
s/DLA_WORKSPACE_QUERY/SLA_WORKSPACE_QUERY/g
s/DLA_TRANSFORM_STANDARD/SLA_TRANSFORM_STANDARD/g
s/DLA_TRANSFORM_GENERAL/SLA_TRANSFORM_GENERAL/g

#RECURSIVE
s/DLA_TRLYAP_RECURSIVE/SLA_TRLYAP_RECURSIVE/g
s/DLA_TRSYLV_RECURSIVE/SLA_TRSYLV_RECURSIVE/g
s/DLA_TRSYLV2_RECURSIVE/SLA_TRSYLV2_RECURSIVE/g
s/DLA_TRSTEIN_RECURSIVE/SLA_TRSTEIN_RECURSIVE/g
s/DLA_TGSYLV_RECURSIVE/SLA_TGSYLV_RECURSIVE/g
s/DLA_TGLYAP_RECURSIVE/SLA_TGLYAP_RECURSIVE/g
s/DLA_TGSTEIN_RECURSIVE/SLA_TGSTEIN_RECURSIVE/g
s/DLA_TGCSYLV_RECURSIVE/SLA_TGCSYLV_RECURSIVE/g
s/DLA_TGCSYLV_DUAL_RECURSIVE/SLA_TGCSYLV_DUAL_RECURSIVE/g


#KERNELS
s/DLA_TRSYLV_KERNEL_44NN/SLA_TRSYLV_KERNEL_44NN/g
s/DLA_TRSYLV_KERNEL_44TN/SLA_TRSYLV_KERNEL_44TN/g
s/DLA_TRSYLV_KERNEL_44NT/SLA_TRSYLV_KERNEL_44NT/g
s/DLA_TRSYLV_KERNEL_44TT/SLA_TRSYLV_KERNEL_44TT/g
s/DLA_TRSYLV2_KERNEL_44NN/SLA_TRSYLV2_KERNEL_44NN/g
s/DLA_TRSYLV2_KERNEL_44TN/SLA_TRSYLV2_KERNEL_44TN/g
s/DLA_TRSYLV2_KERNEL_44NT/SLA_TRSYLV2_KERNEL_44NT/g
s/DLA_TRSYLV2_KERNEL_44TT/SLA_TRSYLV2_KERNEL_44TT/g
s/DLA_TGSYLV_KERNEL_44NN/SLA_TGSYLV_KERNEL_44NN/g
s/DLA_TGSYLV_KERNEL_44TN/SLA_TGSYLV_KERNEL_44TN/g
s/DLA_TGSYLV_KERNEL_44NT/SLA_TGSYLV_KERNEL_44NT/g
s/DLA_TGSYLV_KERNEL_44TT/SLA_TGSYLV_KERNEL_44TT/g
s/DLA_TRLYAP_KERNEL_44N/SLA_TRLYAP_KERNEL_44N/g
s/DLA_TRLYAP_KERNEL_44T/SLA_TRLYAP_KERNEL_44T/g
s/DLA_TGCSYLV_KERNEL_44NN/SLA_TGCSYLV_KERNEL_44NN/g
s/DLA_TGCSYLV_KERNEL_44TN/SLA_TGCSYLV_KERNEL_44TN/g
s/DLA_TGCSYLV_KERNEL_44NT/SLA_TGCSYLV_KERNEL_44NT/g
s/DLA_TGCSYLV_KERNEL_44TT/SLA_TGCSYLV_KERNEL_44TT/g
s/DLA_TGSYLV_KRON_KERNEL/SLA_TGSYLV_KRON_KERNEL/g
s/DLA_TGCSYLV_DUAL_KERNEL_44NN/SLA_TGCSYLV_DUAL_KERNEL_44NN/g
s/DLA_TGCSYLV_DUAL_KERNEL_44TN/SLA_TGCSYLV_DUAL_KERNEL_44TN/g
s/DLA_TGCSYLV_DUAL_KERNEL_44NT/SLA_TGCSYLV_DUAL_KERNEL_44NT/g
s/DLA_TGCSYLV_DUAL_KERNEL_44TT/SLA_TGCSYLV_DUAL_KERNEL_44TT/g

# Level2
s/DLA_TRLYAP_L2/SLA_TRLYAP_L2/g
s/DLA_TRSTEIN_L2/SLA_TRSTEIN_L2/g
s/DLA_TRLYAP_L2_UNOPT/SLA_TRLYAP_L2_UNOPT/g
s/DLA_TRSYLV_L2/SLA_TRSYLV_L2/g
s/DLA_TRSYLV_L2_LOCAL_COPY/SLA_TRSYLV_L2_LOCAL_COPY/g
s/DLA_TRSYLV_L2_LOCAL_COPY_128/SLA_TRSYLV_L2_LOCAL_COPY_128/g
s/DLA_TRSYLV_L2_LOCAL_COPY_32/SLA_TRSYLV_L2_LOCAL_COPY_32/g
s/DLA_TRSYLV_L2_LOCAL_COPY_64/SLA_TRSYLV_L2_LOCAL_COPY_64/g
s/DLA_TRSYLV_L2_LOCAL_COPY_96/SLA_TRSYLV_L2_LOCAL_COPY_96/g
s/DLA_TRSYLV_L2_REORDER/SLA_TRSYLV_L2_REORDER/g
s/DLA_TRSYLV_L2_UNOPT/SLA_TRSYLV_L2_UNOPT/g
s/dla_trsylv_l2_opt_local_copy_xx/sla_trsylv_l2_opt_local_copy_xx/g
s/DLA_TRSYLV2_L2/SLA_TRSYLV2_L2/g
s/DLA_TRSYLV2_L2_LOCAL_COPY/SLA_TRSYLV2_L2_LOCAL_COPY/g
s/DLA_TRSYLV2_L2_LOCAL_COPY_128/SLA_TRSYLV2_L2_LOCAL_COPY_128/g
s/DLA_TRSYLV2_L2_LOCAL_COPY_32/SLA_TRSYLV2_L2_LOCAL_COPY_32/g
s/DLA_TRSYLV2_L2_LOCAL_COPY_64/SLA_TRSYLV2_L2_LOCAL_COPY_64/g
s/DLA_TRSYLV2_L2_LOCAL_COPY_96/SLA_TRSYLV2_L2_LOCAL_COPY_96/g
s/DLA_TRSYLV2_L2_REORDER/SLA_TRSYLV2_L2_REORDER/g
s/DLA_TRSYLV2_L2_UNOPT/SLA_TRSYLV2_L2_UNOPT/g
s/dla_trsylv2_l2_opt_local_copy_xx/sla_trsylv2_l2_opt_local_copy_xx/g
s/DLA_TGSYLV_L2/SLA_TGSYLV_L2/g
s/DLA_TGSYLV_L2_LOCAL_COPY/SLA_TGSYLV_L2_LOCAL_COPY/g
s/DLA_TGSYLV_L2_LOCAL_COPY_128/SLA_TGSYLV_L2_LOCAL_COPY_128/g
s/DLA_TGSYLV_L2_LOCAL_COPY_32/SLA_TGSYLV_L2_LOCAL_COPY_32/g
s/DLA_TGSYLV_L2_LOCAL_COPY_64/SLA_TGSYLV_L2_LOCAL_COPY_64/g
s/DLA_TGSYLV_L2_LOCAL_COPY_96/SLA_TGSYLV_L2_LOCAL_COPY_96/g
s/DLA_TGSYLV_L2_REORDER/SLA_TGSYLV_L2_REORDER/g
s/DLA_TGSYLV_L2_UNOPT/SLA_TGSYLV_L2_UNOPT/g
s/DLA_TGSYLV_L2_ROWWISE/SLA_TGSYLV_L2_ROWWISE/g
s/DLA_TGSYLV_L2_COLWISE/SLA_TGSYLV_L2_COLWISE/g
s/DLA_TGSYLV_GARDINER_LAUB/SLA_TGSYLV_GARDINER_LAUB/g
s/dla_tgsylv_l2_opt_local_copy_xx/sla_tgsylv_l2_opt_local_copy_xx/g
s/DLA_TGLYAP_L2/SLA_TGLYAP_L2/g
s/DLA_TGSTEIN_L2/SLA_TGSTEIN_L2/g
s/DLA_TGLYAP_L2_UNOPT/SLA_TGLYAP_L2_UNOPT/g
s/DLA_TGCSYLV_L2/SLA_TGCSYLV_L2/g
s/DLA_TGCSYLV_L2_LOCAL_COPY/SLA_TGCSYLV_L2_LOCAL_COPY/g
s/DLA_TGCSYLV_L2_LOCAL_COPY_128/SLA_TGCSYLV_L2_LOCAL_COPY_128/g
s/DLA_TGCSYLV_L2_LOCAL_COPY_32/SLA_TGCSYLV_L2_LOCAL_COPY_32/g
s/DLA_TGCSYLV_L2_LOCAL_COPY_64/SLA_TGCSYLV_L2_LOCAL_COPY_64/g
s/DLA_TGCSYLV_L2_LOCAL_COPY_96/SLA_TGCSYLV_L2_LOCAL_COPY_96/g
s/DLA_TGCSYLV_L2_REORDER/SLA_TGCSYLV_L2_REORDER/g
s/DLA_TGCSYLV_L2_UNOPT/SLA_TGCSYLV_L2_UNOPT/g
s/dla_tgcsylv_l2_opt_local_copy_xx/sla_tgcsylv_l2_opt_local_copy_xx/g
s/DLA_TGCSYLV_DUAL_L2/SLA_TGCSYLV_DUAL_L2/g
s/DLA_TGCSYLV_DUAL_L2_LOCAL_COPY/SLA_TGCSYLV_DUAL_L2_LOCAL_COPY/g
s/DLA_TGCSYLV_DUAL_L2_LOCAL_COPY_128/SLA_TGCSYLV_DUAL_L2_LOCAL_COPY_128/g
s/DLA_TGCSYLV_DUAL_L2_LOCAL_COPY_32/SLA_TGCSYLV_DUAL_L2_LOCAL_COPY_32/g
s/DLA_TGCSYLV_DUAL_L2_LOCAL_COPY_64/SLA_TGCSYLV_DUAL_L2_LOCAL_COPY_64/g
s/DLA_TGCSYLV_DUAL_L2_LOCAL_COPY_96/SLA_TGCSYLV_DUAL_L2_LOCAL_COPY_96/g
s/dla_tgcsylv_dual_l2_opt_local_copy_xx/sla_tgcsylv_dual_l2_opt_local_copy_xx/g


# Level3
s/DLA_TRLYAP_L3/SLA_TRLYAP_L3/g
s/DLA_TRSTEIN_L3/SLA_TRSTEIN_L3/g
s/DLA_TRSTEIN_L3_2S/SLA_TRSTEIN_L3_2S/g
s/DLA_TRLYAP_L3_2S/SLA_TRLYAP_L3_2S/g
s/DLA_TRSYLV_L3/SLA_TRSYLV_L3/g
s/DLA_TRSYLV_L3_2S/SLA_TRSYLV_L3_2S/g
s/DLA_TRSYLV2_L3/SLA_TRSYLV2_L3/g
s/DLA_TRSYLV2_L3_2S/SLA_TRSYLV2_L3_2S/g
s/DLA_TGSYLV_L3/SLA_TGSYLV_L3/g
s/DLA_TGSYLV_L3_2S/SLA_TGSYLV_L3_2S/g
s/DLA_TGLYAP_L3/SLA_TGLYAP_L3/g
s/DLA_TGLYAP_L3_2S/SLA_TGLYAP_L3_2S/g
s/DLA_TGSTEIN_L3/SLA_TGSTEIN_L3/g
s/DLA_TGCSYLV_L3/SLA_TGCSYLV_L3/g
s/DLA_TGCSYLV_L3_2S/SLA_TGCSYLV_L3_2S/g
s/DLA_TGCSYLV_DUAL_L3/SLA_TGCSYLV_DUAL_L3/g
s/DLA_TGCSYLV_DUAL_L3_2S/SLA_TGCSYLV_DUAL_L3_2S/g


# DAG
s/DLA_TRLYAP_DAG/SLA_TRLYAP_DAG/g
s/DLA_TRSTEIN_DAG/SLA_TRSTEIN_DAG/g
s/DLA_TRSYLV_DAG/SLA_TRSYLV_DAG/g
s/DLA_TRSYLV2_DAG/SLA_TRSYLV2_DAG/g
s/DLA_TGSYLV_DAG/SLA_TGSYLV_DAG/g
s/DLA_TGLYAP_DAG/SLA_TGLYAP_DAG/g
s/DLA_TGSTEIN_DAG/SLA_TGSTEIN_DAG/g
s/DLA_TGCSYLV_DAG/SLA_TGCSYLV_DAG/g
s/DLA_TGCSYLV_DUAL_DAG/SLA_TGCSYLV_DUAL_DAG/g

# Residual
s/DLA_RESIDUAL_LYAP/SLA_RESIDUAL_LYAP/g
s/DLA_RESIDUAL_GLYAP/SLA_RESIDUAL_GLYAP/g
s/DLA_RESIDUAL_STEIN/SLA_RESIDUAL_STEIN/g
s/DLA_RESIDUAL_GSTEIN/SLA_RESIDUAL_GSTEIN/g
s/DLA_RESIDUAL_SYLV/SLA_RESIDUAL_SYLV/g
s/DLA_RESIDUAL_SYLV2/SLA_RESIDUAL_SYLV2/g
s/DLA_RESIDUAL_GSYLV/SLA_RESIDUAL_GSYLV/g
s/DLA_RESIDUAL_CSYLV/SLA_RESIDUAL_CSYLV/g
s/DLA_RESIDUAL_CSYLV_DUAL/SLA_RESIDUAL_CSYLV_DUAL/g


#DATA Types
s/DOUBLE PRECISION/REAL/g
s/0\.0D0/0.0/g
s/1\.0D0/1.0/g
s/2\.0D0/2.0/g
s/0\.5D0/0.5/g
s/IDLA_/ISLA_/g
s/DBLE(/REAL(/g
s/DSQRT/SQRT/g

#BLAS
s/DGEMM/SGEMM/g
s/DSYMM/SSYMM/g
s/DSYR2K/SSYR2K/g
s/DAXPY/SAXPY/g
s/DSCAL/SSCAL/g
s/DLASET/SLASET/g
s/DLASCL/SLASCL/g
s/DCOPY/SCOPY/g
s/DLACPY/SLACPY/g
s/DTRMM/STRMM/g
s/DTREXC/STREXC/g
s/DTGEX2/STGEX2/g
s/DGESC2/SGESC2/g
s/DGETC2X/SGETC2X/g
s/DSYR2/SSYR2/g
s/DGER/SGER/g
s/DTRMV/STRMV/g
s/DGEMV/SGEMV/g
s/DTRSV/STRSV/g
s/DROT/SROT/g
s/DROTG/SROTG/g
s/DGEES/SGEES/g
s/DTRSYL/STRSYL/g
s/DGGES/SGGES/g
s/DLANGE/SLANGE/g
s/DHGEES/SHGEES/g
s/DHGGES/SHGGES/g

#Categories
s/dbltrsylv/sgltrsylv/g
s/dbltrlyap/sgltrlyap/g
s/dbltrhelp/sgltrhelp/g
s/dbltgsylv/sgltgsylv/g
s/dbltglyap/sgltglyap/g
s/dbltghelp/sgltghelp/g
s/dblaux/sglaux/g
s/dblgelyap/sglgelyap/g
s/dblgesylv/sglgesylv/g
s/dblgglyap/sglgglyap/g
s/dblggsylv/sglggsylv/g


# Frontends
s/DLA_GGCSYLV/SLA_GGCSYLV/g
s/DLA_GGCSYLV_DUAL/SLA_GGCSYLV_DUAL/g
s/DLA_GELYAP/SLA_GELYAP/g
s/DLA_GESTEIN/SLA_GESTEIN/g
s/DLA_GESYLV/SLA_GESYLV/g
s/DLA_GGLYAP/SLA_GGLYAP/g
s/DLA_GGSTEIN/SLA_GGSTEIN/g
s/DLA_GGSYLV/SLA_GGSYLV/g
s/DLA_GELYAP_L3/SLA_GELYAP_L3/g
s/DLA_GELYAP_DAG/SLA_GELYAP_DAG/g
s/DLA_GELYAP_L3_2S/SLA_GELYAP_L3_2S/g
s/DLA_GELYAP_L2/SLA_GELYAP_L2/g
s/DLA_GELYAP_RECURSIVE/SLA_GELYAP_RECURSIVE/g
s/DLA_GESTEIN_L3/SLA_GESTEIN_L3/g
s/DLA_GESTEIN_DAG/SLA_GESTEIN_DAG/g
s/DLA_GESTEIN_L3_2S/SLA_GESTEIN_L3_2S/g
s/DLA_GESTEIN_L2/SLA_GESTEIN_L2/g
s/DLA_GESTEIN_RECURSIVE/SLA_GESTEIN_RECURSIVE/g
s/DLA_GESYLV_L3/SLA_GESYLV_L3/g
s/DLA_GESYLV_DAG/SLA_GESYLV_DAG/g
s/DLA_GESYLV_L3_2S/SLA_GESYLV_L3_2S/g
s/DLA_GESYLV_L2/SLA_GESYLV_L2/g
s/DLA_GESYLV_RECURSIVE/SLA_GESYLV_RECURSIVE/g
s/DLA_GESYLV_LAPACK/SLA_GESYLV_LAPACK/g
s/DLA_GESYLV2_L3/SLA_GESYLV2_L3/g
s/DLA_GESYLV2_DAG/SLA_GESYLV2_DAG/g
s/DLA_GESYLV2_L3_2S/SLA_GESYLV2_L3_2S/g
s/DLA_GESYLV2_L2/SLA_GESYLV2_L2/g
s/DLA_GESYLV2_RECURSIVE/SLA_GESYLV2_RECURSIVE/g
s/DLA_GGLYAP_L3/SLA_GGLYAP_L3/g
s/DLA_GGLYAP_DAG/SLA_GGLYAP_DAG/g
s/DLA_GGLYAP_L3_2S/SLA_GGLYAP_L3_2S/g
s/DLA_GGLYAP_L2/SLA_GGLYAP_L2/g
s/DLA_GGLYAP_RECURSIVE/SLA_GGLYAP_RECURSIVE/g
s/DLA_GGSTEIN_L3/SLA_GGSTEIN_L3/g
s/DLA_GGSTEIN_DAG/SLA_GGSTEIN_DAG/g
s/DLA_GGSTEIN_L3_2S/SLA_GGSTEIN_L3_2S/g
s/DLA_GGSTEIN_L2/SLA_GGSTEIN_L2/g
s/DLA_GGSTEIN_RECURSIVE/SLA_GGSTEIN_RECURSIVE/g
s/DLA_GGSYLV_L3/SLA_GGSYLV_L3/g
s/DLA_GGSYLV_DAG/SLA_GGSYLV_DAG/g
s/DLA_GGSYLV_L3_2S/SLA_GGSYLV_L3_2S/g
s/DLA_GGSYLV_L2/SLA_GGSYLV_L2/g
s/DLA_GGSYLV_RECURSIVE/SLA_GGSYLV_RECURSIVE/g
s/DLA_GGSYLV_GARDINER_LAUB/SLA_GGSYLV_GARDINER_LAUB/g
s/DLA_GGCSYLV_L3/SLA_GGCSYLV_L3/g
s/DLA_GGCSYLV_DAG/SLA_GGCSYLV_DAG/g
s/DLA_GGCSYLV_L3_2S/SLA_GGCSYLV_L3_2S/g
s/DLA_GGCSYLV_L2/SLA_GGCSYLV_L2/g
s/DLA_GGCSYLV_RECURSIVE/SLA_GGCSYLV_RECURSIVE/g

# MODULE NAMES
s/MEPACK_OPTIONS_MACHINE_DOUBLE/MEPACK_OPTIONS_MACHINE_SINGLE/g
s/MEPACK_OPTIONS_BLOCKSIZE_DOUBLE/MEPACK_OPTIONS_BLOCKSIZE_SINGLE/g

# Misc names
s/_double_mb/_single_mb/g
s/_double_nb/_single_nb/g
s/_double_2stage/_single_2stage/g

